title: "Amor e Psican√°lise"
markdown: kramdown
theme: null
permalink: /:path/  # Isso gera URLs como /pages/psicanalise/

defaults:
  - scope:
      path: "pages"
    values:
      layout: default
  - scope:
      path: "artigos"
    values:
      layout: default
